export const brunchMovies = [
    'The Wrong Missy',
    'Grandma\'s Boy',
    'Dogma',
    'Cable Guy',
    'Amateur Night',
    'Little Nicky',
    'My Cousin Vinny',
    'The Hangover',
    'The Hangover part II',
    'The Hangover part III',
    'Adventureland',
    'Meet the Parents',
    'Meet the Fockers',
    'Little Fockers',
    'Out Cold',
    'Something About Mary',
    'American Pie',
    '50 First Dates',
    'Kingpin',
    'Friday',
    'Next Friday',
    'Friday After Next',
    'Good Boys',
    'Harold & Kumar Go to White Castle', 
    'Please Don\'t Destroy: The Treasure of Foggy Mountain',
    'The Heartbreak Kid',
    'Horrible Bosses',
    'Wedding Crashers',
    'Idiocracy',
    'Bad Words',
    'Dirty Grandpa',
    'The Big Lebowski',
    'Couples Retreat',
    'The Proposal',
    'The Duplex',
    'The Big Short',
    'Waiting...',
    'Identity Thief',
    'Saving Silverman',
    'The Devil Wears Prada',
    'American Ultra',
    'Orange County',
    'Palm Springs',
    'Election',
    'Legally Blonde',
    'Legally Blonde 2',
    'Life After Beth',
    'Napoleon Dynamite',
    'Office Space',
    'Pleasantville',
    'Unfinished Business',
    'Jurassic Park',
    'Men In Black',
    'Men In Black II'
];