export const brunchMovies = [
    'The Wrong Missy',
    'Meet the Parents',
    'Meet the Fockers',
    'Little Fockers',
    'Out Cold',
    'Something About Mary',
    'American Pie',
    '50 First Dates',
    'Kingpin',
    'Friday',
    'Next Friday',
    'Friday After Next',
    'Good Boys',
    'Harold and Kumar', 
    'Please dont destroy the treasure of foggy mountain',
    'The Heart Break Kid',
    'Horrible Bosses',
    'Wedding Crashers',
    'Idiocracy',
    'Bad Words',
    'Dirty Grandpa',
    'The Big Lebowski',
    'Couples Retreat',
    'The Proposal',
    'The Duplex',
    'The Big Short',
    'Waiting',
    'Identity Thief',
    'Saving Silverman',
    'The Devil Wears Prada',
    'American Ultra',
    'Orange County',
    'Palm Springs',
    'Election',
    'Legally Blonde',
    'Legally Blonde 2',
    'Life After Beth',
    'Napoleon Dynamite',
    'Office Space',
    'Pleasentville',
    'Unfinished Business',
    'Jurassic Park',
    'Men In Black',
    'Men In Black 2'
];