export const christmasMovies = [
    'Deck The Halls',
    'Thanksgiving (Prime)',
    'Friendsgiving',
    'A Christmas Story',
    'The Santa Clause',
    'Christmas Vacation',
    'Eight Crazy Nights', 
    'The Muppet Christmas Carol',
    'Scrooged',
    'How the Grinch Stole Christmas',
    'How the Grinch Stole Christmas!',
    'Bad Santa 2',
    'Klaus',
    'Office Christmas Party',
    'Bad Santa',
    'Christmas With the Kranks',
    '8 Bit Christmas',
    'Friday After Next',
    'A Very Harold & Kumar Christmas',
    'Home Alone',
    'Home Alone 2: Lost in New York',
    'Krampus',
    'Batman Returns',
    'Elf',
    'Rudolph the Red-Nosed Reindeer',
    'Mickey\'s Christmas Carol',
    'Fred Claus',
    'Four Christmases'
];