export const christmasMovies = [
    'Deck The Halls',
    'Thanksgiving (Prime)',
    'Friendsgiving',
    'Christmas Story',
    'Santa Claus',
    'Christmas Vacation',
    'Eight Crazy Nights', 
    'The Muppet Christmas Carol',
    'Scrooged',
    'The Grinch',
    'How the Grinch Stole Christmas',
    'Bad Santa 2',
    'Klaus',
    'Office Christmas Party',
    'Bad Santa',
    'Christmas With the Kranks',
    '8 Bit Christmas',
    'Friday After Next',
    'A Very Harold & Kumar Christmas',
    'Home Alone',
    'Home Alone 2',
    'Krampus',
    'Batman Returns',
    'Elf',
    'Rudolph the Red-Nosed Reindeer',
    'Mickey\'s Christmas Carol',
    'Fred Claus',
    'Four Christmases'
];