export const christmasMovies = [
    'Deck The Halls',
    'Thanksgiving (Prime)',
    'Friendsgiving',
    'Christmas Story',
    'Santa Claus',
    'Christmas Vacation',
    '8 Crazy Nights', 
    'Muppets Christmas',
    'Scrooged',
    'The Grinch Movie',
    'The Grinch Cartoon',
    'Bad Santa 2',
    'Klaus',
    'Office Christmas Party Movie',
    'Bad Santa',
    'Christmas With the Kranks',
    '8 Bit Christmas',
    'Friday After Next',
    'Harold and Kumar Christmas',
    'Home Alone',
    'Home Alone 2',
    'Krampus',
    'Batman Returns',
    'Elf',
    'Rankin/Bass CBS Christmas Special',
    'Mickeys Christmas Carol',
    'Fred Claus',
    'Four Christmases'
];